# AUTO-GENERATED FROM contracts/artifact/v1.0.json
# DO NOT EDIT MANUALLY!
#
# Artifact Protocol v1.0.0
# Layer: backend
# Generated by: contracts/artifact/generate_artifact_types.py
#
# This file is generated from the shared artifact JSON Schema.
# To update, edit contracts/artifact/v1.0.json and run the generator.

from enum import Enum
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field, field_validator

try:
    from taskingai_contracts import validate_artifact_list as _contract_validate_artifact_list
    HAS_RUNTIME_SCHEMA_VALIDATION = True
except ImportError:
    HAS_RUNTIME_SCHEMA_VALIDATION = False

__all__ = [
    "ArtifactType", "Artifact", "normalize_artifact", "summarize_artifact", "parse_and_normalize_artifacts", "MAX_ARTIFACT_CONTENT_LENGTH", "MAX_ARTIFACT_TITLE_LENGTH", "MAX_ARTIFACTS_PER_TOOL",
]

MAX_ARTIFACT_CONTENT_LENGTH = 4096
MAX_ARTIFACT_TITLE_LENGTH = 128
MAX_ARTIFACTS_PER_TOOL = 10


class ArtifactType(str, Enum):
    """
    The type of the artifact.
    Only these 5 types are supported across all layers.
    Source: contracts/artifact/v1.0.json#/definitions/ArtifactType
    """
    TEXT = "text"
    IMAGE = "image"
    FILE = "file"
    JSON = "json"
    TABLE = "table"

    @classmethod
    def has_value(cls, value: str) -> bool:
        return value in cls._value2member_map_


class Artifact(BaseModel):
    """
    Standard artifact data transfer object (DTO).
    All layers must use this exact schema.
    Source: contracts/artifact/v1.0.json#/definitions/Artifact
    """

    type: ArtifactType = Field(
        ...,
        description="The type of the artifact.",
    )
    mime_type: str = Field(
        ...,
        min_length=1,
        max_length=128,
        description="The MIME type of the artifact. Must be in 'type/subtype' format, lowercase.",
    )
    title: Optional[str] = Field(
        None,
        max_length=MAX_ARTIFACT_TITLE_LENGTH,
        description="The display title of the artifact. Will be truncated if exceeds max length.",
    )
    content: Optional[str] = Field(
        None,
        description="The text content of the artifact (for text, json, table, etc.). Will be truncated if exceeds max content length.",
    )
    preview_url: Optional[str] = Field(
        None,
        description="The preview image URL of the artifact.",
    )
    download_url: Optional[str] = Field(
        None,
        description="The download URL of the artifact.",
    )
    size: Optional[int] = Field(
        None,
        ge=0,
        description="The size of the artifact in bytes.",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata for the artifact.",
    )

    @field_validator("mime_type")
    @classmethod
    def validate_mime_type(cls, v: str) -> str:
        if "/" not in v:
            raise ValueError("Invalid MIME type format")
        return v.lower()

    @field_validator("title")
    @classmethod
    def trim_title(cls, v: Optional[str]) -> Optional[str]:
        if v and len(v) > MAX_ARTIFACT_TITLE_LENGTH:
            return v[: MAX_ARTIFACT_TITLE_LENGTH - 3] + "..."
        return v


def _default_mime_type_for_type(artifact_type: str) -> str:
    """
    Default MIME types for each artifact type when not explicitly provided.
    Source: contracts/artifact/v1.0.json#/properties/defaultMimeTypes
    """
    type_map = {
        "text": "text/plain",
        "image": "image/png",
        "file": "application/octet-stream",
        "json": "application/json",
        "table": "application/json",
    }
    return type_map.get(artifact_type, "application/octet-stream")


def normalize_artifact(artifact: Dict[str, Any]) -> Artifact:
    """
    Normalize a raw artifact dict to an Artifact model instance.
    Validates against the shared schema and applies defaults.
    """
    if "type" not in artifact:
        raise ValueError("Artifact type is required")
    if "mime_type" not in artifact:
        artifact["mime_type"] = _default_mime_type_for_type(artifact["type"])
    if "metadata" not in artifact:
        artifact["metadata"] = {}

    return Artifact(**artifact)


def summarize_artifact(artifact: Artifact, max_content_length: int = MAX_ARTIFACT_CONTENT_LENGTH) -> Artifact:
    """
    Truncate artifact content and title if they exceed maximum lengths.
    """
    if artifact.content and len(artifact.content) > max_content_length:
        truncated = artifact.content[:max_content_length]
        artifact.content = truncated + "..."
        if artifact.size is None:
            artifact.size = len(artifact.content.encode("utf-8"))

    if artifact.title and len(artifact.title) > MAX_ARTIFACT_TITLE_LENGTH:
        artifact.title = artifact.title[: MAX_ARTIFACT_TITLE_LENGTH - 3] + "..."

    return artifact


def parse_and_normalize_artifacts(
    artifacts_data: Optional[List[Dict[str, Any]]],
) -> List[Artifact]:
    """
    Parse and normalize artifacts from raw dict data.
    Only validates and summarizes - legacy conversion is done at plugin layer.
    Validates against shared JSON Schema at runtime if available.
    """
    result: List[Artifact] = []

    if artifacts_data:
        if HAS_RUNTIME_SCHEMA_VALIDATION:
            is_valid, errors = _contract_validate_artifact_list(artifacts_data)
            if not is_valid:
                import logging
                logger = logging.getLogger(__name__)
                logger.warning("Artifact schema validation failed: %s", errors)

        for artifact_dict in artifacts_data:
            try:
                artifact = normalize_artifact(artifact_dict)
                artifact = summarize_artifact(artifact)
                result.append(artifact)
            except Exception:
                continue

    if len(result) > MAX_ARTIFACTS_PER_TOOL:
        result = result[:MAX_ARTIFACTS_PER_TOOL]

    return result
