// AUTO-GENERATED FROM contracts/artifact/v1.0.json
// DO NOT EDIT MANUALLY!
//
// Artifact Protocol v1.0.0
// Layer: frontend
// Generated by: contracts/artifact/generate_artifact_types.py
//
// This file is generated from the shared artifact JSON Schema.
// To update, edit contracts/artifact/v1.0.json and run the generator.

/**
 * Artifact Protocol Constants
 * Source: contracts/artifact/v1.0.json#/properties/constants
 */
export const ARTIFACT_CONSTANTS = {
  MAX_ARTIFACT_CONTENT_LENGTH: 4096,
  MAX_ARTIFACT_TITLE_LENGTH: 128,
  MAX_ARTIFACTS_PER_TOOL: 10,
} as const;

/**
 * The type of the artifact.
 * Only these 5 types are supported across all layers.
 * Source: contracts/artifact/v1.0.json#/definitions/ArtifactType
 */
export type ArtifactType = 'text' | 'image' | 'file' | 'json' | 'table';

/**
 * Standard artifact data transfer object (DTO).
 * All layers must use this exact schema.
 * Source: contracts/artifact/v1.0.json#/definitions/Artifact
 */
export interface Artifact {
  /** The type of the artifact. */
  type: ArtifactType;

  /** The MIME type of the artifact. Must be in 'type/subtype' format, lowercase. */
  mime_type: string;

  /** The display title of the artifact. Will be truncated if exceeds max length. */
  title?: string;

  /** The text content of the artifact (for text, json, table, etc.). Will be truncated if exceeds max content length. */
  content?: string;

  /** The preview image URL of the artifact. */
  preview_url?: string;

  /** The download URL of the artifact. */
  download_url?: string;

  /** The size of the artifact in bytes. */
  size?: number;

  /** Additional metadata for the artifact. */
  metadata?: Record<string, any>;
}

export interface MessageContent {
  text: string;
  artifacts?: Artifact[];
}

export interface Message {
  object: string;
  assistant_id: string;
  chat_id: string;
  message_id: string;
  role: 'user' | 'assistant';
  content: MessageContent;
  num_tokens: number;
  metadata: Record<string, any>;
  created_timestamp: number;
  updated_timestamp: number;
}
