# AUTO-GENERATED FROM contracts/artifact/v1.0.json
# DO NOT EDIT MANUALLY!
#
# Artifact Protocol v1.0.0
# Layer: plugin
# Generated by: contracts/artifact/generate_artifact_types.py
#
# This file is generated from the shared artifact JSON Schema.
# To update, edit contracts/artifact/v1.0.json and run the generator.

from enum import Enum
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field, field_validator

try:
    from taskingai_contracts import validate_artifact_list as _contract_validate_artifact_list
    HAS_RUNTIME_SCHEMA_VALIDATION = True
except ImportError:
    HAS_RUNTIME_SCHEMA_VALIDATION = False

__all__ = [
    "ArtifactType", "Artifact", "PluginOutputWithArtifacts", "convert_legacy_data_to_artifacts", "summarize_artifact", "normalize_and_summarize_artifacts", "MAX_ARTIFACT_CONTENT_LENGTH", "MAX_ARTIFACT_TITLE_LENGTH", "MAX_ARTIFACTS_PER_TOOL",
]

MAX_ARTIFACT_CONTENT_LENGTH = 4096
MAX_ARTIFACT_TITLE_LENGTH = 128
MAX_ARTIFACTS_PER_TOOL = 10


class ArtifactType(str, Enum):
    """
    The type of the artifact.
    Only these 5 types are supported across all layers.
    Source: contracts/artifact/v1.0.json#/definitions/ArtifactType
    """
    TEXT = "text"
    IMAGE = "image"
    FILE = "file"
    JSON = "json"
    TABLE = "table"

    @classmethod
    def has_value(cls, value: str) -> bool:
        return value in cls._value2member_map_


class Artifact(BaseModel):
    """
    Standard artifact data transfer object (DTO).
    All layers must use this exact schema.
    Source: contracts/artifact/v1.0.json#/definitions/Artifact
    """

    type: ArtifactType = Field(
        ...,
        description="The type of the artifact.",
    )
    mime_type: str = Field(
        ...,
        min_length=1,
        max_length=128,
        description="The MIME type of the artifact. Must be in 'type/subtype' format, lowercase.",
    )
    title: Optional[str] = Field(
        None,
        max_length=MAX_ARTIFACT_TITLE_LENGTH,
        description="The display title of the artifact. Will be truncated if exceeds max length.",
    )
    content: Optional[str] = Field(
        None,
        description="The text content of the artifact (for text, json, table, etc.). Will be truncated if exceeds max content length.",
    )
    preview_url: Optional[str] = Field(
        None,
        description="The preview image URL of the artifact.",
    )
    download_url: Optional[str] = Field(
        None,
        description="The download URL of the artifact.",
    )
    size: Optional[int] = Field(
        None,
        ge=0,
        description="The size of the artifact in bytes.",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata for the artifact.",
    )

    @field_validator("mime_type")
    @classmethod
    def validate_mime_type(cls, v: str) -> str:
        if "/" not in v:
            raise ValueError("Invalid MIME type format")
        return v.lower()

    @field_validator("title")
    @classmethod
    def trim_title(cls, v: Optional[str]) -> Optional[str]:
        if v and len(v) > MAX_ARTIFACT_TITLE_LENGTH:
            return v[: MAX_ARTIFACT_TITLE_LENGTH - 3] + "..."
        return v


class PluginOutputWithArtifacts(BaseModel):
    status: int = Field(200, description="The status code of the plugin output.")
    data: Dict = Field(default_factory=dict, description="The data content of the plugin output.")
    artifacts: List[Artifact] = Field(
        default_factory=list,
        description="The list of artifacts generated by the plugin.",
    )


_MIME_TYPE_MAP = {
    "png": "image/png",
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "gif": "image/gif",
    "webp": "image/webp",
    "svg": "image/svg+xml",
    "pdf": "application/pdf",
    "txt": "text/plain",
    "md": "text/markdown",
    "html": "text/html",
    "json": "application/json",
    "csv": "text/csv",
    "mp3": "audio/mpeg",
    "wav": "audio/wav",
    "mp4": "video/mp4",
    "webm": "video/webm",
    "zip": "application/zip",
}


def _guess_mime_type_from_url(url: str) -> str:
    lower_url = url.lower()
    for ext, mime in _MIME_TYPE_MAP.items():
        if f".{ext}" in lower_url:
            return mime
    return "application/octet-stream"


def _guess_mime_type_from_content(content: str) -> str:
    try:
        import json
        json.loads(content)
        return "application/json"
    except Exception:
        pass
    if content.strip().startswith("<!DOCTYPE") or content.strip().startswith("<html"):
        return "text/html"
    if content.strip().startswith("```"):
        return "text/markdown"
    return "text/plain"


def convert_legacy_data_to_artifacts(data: Dict) -> List[Artifact]:
    """
    Convert legacy plugin output data to standard artifacts.
    Supports: url, image_url, file_url, content, text, json, table fields.
    """
    artifacts: List[Artifact] = []

    if "url" in data and isinstance(data["url"], str):
        url = data["url"]
        mime_type = _guess_mime_type_from_url(url)
        artifact_type = ArtifactType.FILE
        if mime_type.startswith("image/"):
            artifact_type = ArtifactType.IMAGE
        elif mime_type.startswith("text/"):
            artifact_type = ArtifactType.TEXT

        artifacts.append(
            Artifact(
                type=artifact_type,
                mime_type=mime_type,
                title=data.get("title") or data.get("name") or "File",
                download_url=url,
                preview_url=url if artifact_type == ArtifactType.IMAGE else None,
                size=data.get("size"),
                metadata={k: v for k, v in data.items() if k not in {"url", "title", "name", "size"}},
            )
        )

    elif "image_url" in data and isinstance(data["image_url"], str):
        url = data["image_url"]
        artifacts.append(
            Artifact(
                type=ArtifactType.IMAGE,
                mime_type=_guess_mime_type_from_url(url),
                title=data.get("title") or "Image",
                download_url=url,
                preview_url=url,
                size=data.get("size"),
                metadata={k: v for k, v in data.items() if k not in {"image_url", "title", "size"}},
            )
        )

    elif "file_url" in data and isinstance(data["file_url"], str):
        url = data["file_url"]
        artifacts.append(
            Artifact(
                type=ArtifactType.FILE,
                mime_type=_guess_mime_type_from_url(url),
                title=data.get("title") or data.get("name") or "File",
                download_url=url,
                size=data.get("size"),
                metadata={k: v for k, v in data.items() if k not in {"file_url", "title", "name", "size"}},
            )
        )

    elif "json" in data and isinstance(data["json"], (dict, list)):
        import json
        json_str = json.dumps(data["json"], ensure_ascii=False)
        artifacts.append(
            Artifact(
                type=ArtifactType.JSON,
                mime_type="application/json",
                title=data.get("title") or "JSON Data",
                content=json_str,
                size=len(json_str.encode("utf-8")),
                metadata={k: v for k, v in data.items() if k not in {"json", "title"}},
            )
        )

    elif "table" in data and isinstance(data["table"], list):
        import json
        table_str = json.dumps(data["table"], ensure_ascii=False)
        artifacts.append(
            Artifact(
                type=ArtifactType.TABLE,
                mime_type="application/json",
                title=data.get("title") or "Table Data",
                content=table_str,
                size=len(table_str.encode("utf-8")),
                metadata={k: v for k, v in data.items() if k not in {"table", "title"}},
            )
        )

    elif "content" in data and isinstance(data["content"], str):
        content = data["content"]
        mime_type = _guess_mime_type_from_content(content)
        artifact_type = ArtifactType.TEXT
        if mime_type == "application/json":
            artifact_type = ArtifactType.JSON

        artifacts.append(
            Artifact(
                type=artifact_type,
                mime_type=mime_type,
                title=data.get("title") or "Content",
                content=content,
                size=len(content.encode("utf-8")),
                metadata={k: v for k, v in data.items() if k not in {"content", "title", "type"}},
            )
        )

    elif "text" in data and isinstance(data["text"], str):
        text = data["text"]
        artifacts.append(
            Artifact(
                type=ArtifactType.TEXT,
                mime_type="text/plain",
                title=data.get("title") or "Text",
                content=text,
                size=len(text.encode("utf-8")),
                metadata={k: v for k, v in data.items() if k not in {"text", "title"}},
            )
        )

    return artifacts


def summarize_artifact(artifact: Artifact, max_content_length: int = MAX_ARTIFACT_CONTENT_LENGTH) -> Artifact:
    """
    Truncate artifact content and title if they exceed maximum lengths.
    """
    if artifact.content and len(artifact.content) > max_content_length:
        truncated = artifact.content[:max_content_length]
        artifact.content = truncated + "..."
        if artifact.size is None:
            artifact.size = len(artifact.content.encode("utf-8"))

    if artifact.title and len(artifact.title) > MAX_ARTIFACT_TITLE_LENGTH:
        artifact.title = artifact.title[: MAX_ARTIFACT_TITLE_LENGTH - 3] + "..."

    return artifact


def normalize_and_summarize_artifacts(
    artifacts: Optional[List[Artifact]],
    legacy_data: Optional[Dict] = None,
) -> List[Artifact]:
    """
    Normalize and summarize artifacts.
    First tries to process new artifacts, falls back to legacy data conversion.
    Validates against shared JSON Schema at runtime if available.
    """
    result: List[Artifact] = []

    if artifacts:
        if HAS_RUNTIME_SCHEMA_VALIDATION:
            artifact_dicts = [a.model_dump() for a in artifacts]
            is_valid, errors = _contract_validate_artifact_list(artifact_dicts)
            if not is_valid:
                import logging
                logger = logging.getLogger(__name__)
                logger.warning("Artifact schema validation failed: %s", errors)

        for artifact in artifacts:
            try:
                summarize_artifact(artifact)
                result.append(artifact)
            except Exception:
                continue

    if not result and legacy_data:
        result = convert_legacy_data_to_artifacts(legacy_data)
        for artifact in result:
            summarize_artifact(artifact)

    if len(result) > MAX_ARTIFACTS_PER_TOOL:
        result = result[:MAX_ARTIFACTS_PER_TOOL]

    return result
