from enum import Enum
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field

__all__ = [
    "ArtifactType",
    "Artifact",
    "PluginOutputWithArtifacts",
    "convert_legacy_data_to_artifacts",
]


class ArtifactType(str, Enum):
    TEXT = "text"
    IMAGE = "image"
    FILE = "file"
    LINK = "link"
    CODE = "code"
    AUDIO = "audio"
    VIDEO = "video"


class Artifact(BaseModel):
    type: ArtifactType = Field(
        ...,
        description="The type of the artifact.",
    )
    mime_type: str = Field(
        ...,
        description="The MIME type of the artifact.",
        examples=["text/plain", "image/png", "application/pdf"],
    )
    title: Optional[str] = Field(
        None,
        description="The display title of the artifact.",
    )
    content: Optional[str] = Field(
        None,
        description="The text content of the artifact (for text, code, etc.).",
    )
    preview_url: Optional[str] = Field(
        None,
        description="The preview image URL of the artifact.",
    )
    download_url: Optional[str] = Field(
        None,
        description="The download URL of the artifact.",
    )
    size: Optional[int] = Field(
        None,
        ge=0,
        description="The size of the artifact in bytes.",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata for the artifact.",
    )


class PluginOutputWithArtifacts(BaseModel):
    status: int = Field(200, description="The status code of the plugin output.")
    data: Dict = Field(default_factory=dict, description="The data content of the plugin output.")
    artifacts: List[Artifact] = Field(
        default_factory=list,
        description="The list of artifacts generated by the plugin.",
    )


_MIME_TYPE_MAP = {
    "png": "image/png",
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "gif": "image/gif",
    "webp": "image/webp",
    "svg": "image/svg+xml",
    "pdf": "application/pdf",
    "txt": "text/plain",
    "md": "text/markdown",
    "html": "text/html",
    "json": "application/json",
    "csv": "text/csv",
    "mp3": "audio/mpeg",
    "wav": "audio/wav",
    "mp4": "video/mp4",
    "webm": "video/webm",
    "zip": "application/zip",
}


def _guess_mime_type_from_url(url: str) -> str:
    lower_url = url.lower()
    for ext, mime in _MIME_TYPE_MAP.items():
        if f".{ext}" in lower_url:
            return mime
    return "application/octet-stream"


def _guess_mime_type_from_content(content: str) -> str:
    try:
        import json
        json.loads(content)
        return "application/json"
    except Exception:
        pass
    if content.strip().startswith("<!DOCTYPE") or content.strip().startswith("<html"):
        return "text/html"
    if content.strip().startswith("```"):
        return "text/markdown"
    return "text/plain"


def convert_legacy_data_to_artifacts(data: Dict) -> List[Artifact]:
    artifacts: List[Artifact] = []

    if "url" in data and isinstance(data["url"], str):
        url = data["url"]
        mime_type = _guess_mime_type_from_url(url)
        artifact_type = ArtifactType.FILE
        if mime_type.startswith("image/"):
            artifact_type = ArtifactType.IMAGE
        elif mime_type.startswith("audio/"):
            artifact_type = ArtifactType.AUDIO
        elif mime_type.startswith("video/"):
            artifact_type = ArtifactType.VIDEO
        elif mime_type.startswith("text/"):
            artifact_type = ArtifactType.TEXT

        artifacts.append(
            Artifact(
                type=artifact_type,
                mime_type=mime_type,
                title=data.get("title") or data.get("name") or "File",
                download_url=url,
                preview_url=url if artifact_type == ArtifactType.IMAGE else None,
                size=data.get("size"),
                metadata={k: v for k, v in data.items() if k not in {"url", "title", "name", "size"}},
            )
        )

    elif "image_url" in data and isinstance(data["image_url"], str):
        url = data["image_url"]
        artifacts.append(
            Artifact(
                type=ArtifactType.IMAGE,
                mime_type=_guess_mime_type_from_url(url),
                title=data.get("title") or "Image",
                download_url=url,
                preview_url=url,
                size=data.get("size"),
                metadata={k: v for k, v in data.items() if k not in {"image_url", "title", "size"}},
            )
        )

    elif "file_url" in data and isinstance(data["file_url"], str):
        url = data["file_url"]
        artifacts.append(
            Artifact(
                type=ArtifactType.FILE,
                mime_type=_guess_mime_type_from_url(url),
                title=data.get("title") or data.get("name") or "File",
                download_url=url,
                size=data.get("size"),
                metadata={k: v for k, v in data.items() if k not in {"file_url", "title", "name", "size"}},
            )
        )

    elif "content" in data and isinstance(data["content"], str):
        content = data["content"]
        mime_type = _guess_mime_type_from_content(content)
        artifact_type = ArtifactType.TEXT
        if mime_type == "application/json":
            artifact_type = ArtifactType.CODE
        elif data.get("type") == "code":
            artifact_type = ArtifactType.CODE

        artifacts.append(
            Artifact(
                type=artifact_type,
                mime_type=mime_type,
                title=data.get("title") or "Content",
                content=content,
                size=len(content.encode("utf-8")),
                metadata={k: v for k, v in data.items() if k not in {"content", "title", "type"}},
            )
        )

    elif "text" in data and isinstance(data["text"], str):
        text = data["text"]
        artifacts.append(
            Artifact(
                type=ArtifactType.TEXT,
                mime_type="text/plain",
                title=data.get("title") or "Text",
                content=text,
                size=len(text.encode("utf-8")),
                metadata={k: v for k, v in data.items() if k not in {"text", "title"}},
            )
        )

    return artifacts
