from abc import ABC, abstractmethod
from typing import Dict, Optional, List
from app.models import BundleCredentials
from app.models.artifact import Artifact, convert_legacy_data_to_artifacts
from pydantic import BaseModel, Field
import logging

logger = logging.getLogger(__name__)


class PluginOutput(BaseModel):
    status: int = Field(200)
    data: Dict = Field(default_factory=dict)
    artifacts: List[Artifact] = Field(
        default_factory=list,
        description="List of artifacts generated by the plugin.",
    )

    @classmethod
    def from_legacy(cls, status: int, data: Dict) -> "PluginOutput":
        artifacts = convert_legacy_data_to_artifacts(data)
        return cls(status=status, data=data, artifacts=artifacts)


class PluginInput(BaseModel):
    input_params: Dict = Field(...)
    project_id: Optional[str] = Field(None)


class PluginHandler(ABC):
    def __init__(self):
        pass

    @abstractmethod
    async def execute(
        self,
        credentials: BundleCredentials,
        plugin_input: PluginInput,
    ) -> PluginOutput:
        raise NotImplementedError
