#!/usr/bin/env python3
"""
Artifact Schema Code Generator
===============================

Generates Python and TypeScript type definitions from the shared artifact JSON Schema.
This is the single source of truth for artifact type definitions across all layers.

Usage:
    python generate_artifact_types.py
"""

import json
import os
import sys
from pathlib import Path

SCHEMA_PATH = Path(__file__).parent / "v1.0.json"
BACKEND_OUTPUT = Path(__file__).parent.parent.parent / "backend" / "app" / "models" / "tool" / "artifact.py"
PLUGIN_OUTPUT = Path(__file__).parent.parent.parent / "plugin" / "app" / "models" / "artifact.py"
FRONTEND_OUTPUT = Path(__file__).parent.parent.parent / "frontend" / "src" / "types" / "artifact.ts"

# ── npm package outputs ──────────────────────────────────────────────
NPM_PKG = Path(__file__).parent.parent / "npm"
NPM_TYPES_OUTPUT = NPM_PKG / "src" / "artifact" / "types.ts"
NPM_SCHEMA_OUTPUT = NPM_PKG / "src" / "artifact" / "schemas" / "v1.0.json"

# ── python package schema ────────────────────────────────────────────
PY_PKG_SCHEMA = Path(__file__).parent.parent / "python" / "taskingai_contracts" / "artifact" / "schemas" / "v1.0.json"


def load_schema() -> dict:
    with open(SCHEMA_PATH, "r") as f:
        return json.load(f)


def generate_python_models(schema: dict, layer: str) -> str:
    """Generate Python model code for backend or plugin layer."""
    constants = schema["properties"]["constants"]["properties"]
    default_mime_types = schema["properties"]["defaultMimeTypes"]["properties"]
    mime_type_map = schema["properties"]["mimeTypeMap"]["properties"]
    artifact_schema = schema["definitions"]["Artifact"]
    artifact_types = schema["definitions"]["ArtifactType"]["enum"]

    max_content = constants["MAX_ARTIFACT_CONTENT_LENGTH"]["const"]
    max_title = constants["MAX_ARTIFACT_TITLE_LENGTH"]["const"]
    max_artifacts = constants["MAX_ARTIFACTS_PER_TOOL"]["const"]

    if layer == "plugin":
        all_list = [
            '"ArtifactType"',
            '"Artifact"',
            '"PluginOutputWithArtifacts"',
            '"convert_legacy_data_to_artifacts"',
            '"summarize_artifact"',
            '"normalize_and_summarize_artifacts"',
            '"MAX_ARTIFACT_CONTENT_LENGTH"',
            '"MAX_ARTIFACT_TITLE_LENGTH"',
            '"MAX_ARTIFACTS_PER_TOOL"',
        ]
        extra_imports = "from pydantic import BaseModel, Field, field_validator"
        extra_module_imports = '''
try:
    from taskingai_contracts import validate_artifact_list as _contract_validate_artifact_list
    HAS_RUNTIME_SCHEMA_VALIDATION = True
except ImportError:
    HAS_RUNTIME_SCHEMA_VALIDATION = False
'''
    else:  # backend
        all_list = [
            '"ArtifactType"',
            '"Artifact"',
            '"normalize_artifact"',
            '"summarize_artifact"',
            '"parse_and_normalize_artifacts"',
            '"MAX_ARTIFACT_CONTENT_LENGTH"',
            '"MAX_ARTIFACT_TITLE_LENGTH"',
            '"MAX_ARTIFACTS_PER_TOOL"',
        ]
        extra_imports = "from pydantic import BaseModel, Field, field_validator"
        extra_module_imports = '''
try:
    from taskingai_contracts import validate_artifact_list as _contract_validate_artifact_list
    HAS_RUNTIME_SCHEMA_VALIDATION = True
except ImportError:
    HAS_RUNTIME_SCHEMA_VALIDATION = False
'''

    artifact_types_str = ", ".join(f'"{t}"' for t in artifact_types)

    type_map_lines = []
    for ext, mime_obj in mime_type_map.items():
        mime_value = mime_obj["const"] if isinstance(mime_obj, dict) and "const" in mime_obj else mime_obj
        type_map_lines.append(f'    "{ext}": "{mime_value}",')

    default_mime_lines = []
    for t, mime_obj in default_mime_types.items():
        mime_value = mime_obj["const"] if isinstance(mime_obj, dict) and "const" in mime_obj else mime_obj
        default_mime_lines.append(f'        "{t}": "{mime_value}",')

    code = f'''# AUTO-GENERATED FROM contracts/artifact/v1.0.json
# DO NOT EDIT MANUALLY!
#
# Artifact Protocol v{schema["version"]}
# Layer: {layer}
# Generated by: contracts/artifact/generate_artifact_types.py
#
# This file is generated from the shared artifact JSON Schema.
# To update, edit contracts/artifact/v1.0.json and run the generator.

from enum import Enum
from typing import Optional, Dict, Any, List
{extra_imports}
{extra_module_imports}
__all__ = [
    {", ".join(all_list)},
]

MAX_ARTIFACT_CONTENT_LENGTH = {max_content}
MAX_ARTIFACT_TITLE_LENGTH = {max_title}
MAX_ARTIFACTS_PER_TOOL = {max_artifacts}


class ArtifactType(str, Enum):
    """
    The type of the artifact.
    Only these 5 types are supported across all layers.
    Source: contracts/artifact/v1.0.json#/definitions/ArtifactType
    """
    TEXT = "text"
    IMAGE = "image"
    FILE = "file"
    JSON = "json"
    TABLE = "table"

    @classmethod
    def has_value(cls, value: str) -> bool:
        return value in cls._value2member_map_


class Artifact(BaseModel):
    """
    Standard artifact data transfer object (DTO).
    All layers must use this exact schema.
    Source: contracts/artifact/v1.0.json#/definitions/Artifact
    """

    type: ArtifactType = Field(
        ...,
        description="The type of the artifact.",
    )
    mime_type: str = Field(
        ...,
        min_length=1,
        max_length=128,
        description="The MIME type of the artifact. Must be in 'type/subtype' format, lowercase.",
    )
    title: Optional[str] = Field(
        None,
        max_length=MAX_ARTIFACT_TITLE_LENGTH,
        description="The display title of the artifact. Will be truncated if exceeds max length.",
    )
    content: Optional[str] = Field(
        None,
        description="The text content of the artifact (for text, json, table, etc.). Will be truncated if exceeds max content length.",
    )
    preview_url: Optional[str] = Field(
        None,
        description="The preview image URL of the artifact.",
    )
    download_url: Optional[str] = Field(
        None,
        description="The download URL of the artifact.",
    )
    size: Optional[int] = Field(
        None,
        ge=0,
        description="The size of the artifact in bytes.",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata for the artifact.",
    )

    @field_validator("mime_type")
    @classmethod
    def validate_mime_type(cls, v: str) -> str:
        if "/" not in v:
            raise ValueError("Invalid MIME type format")
        return v.lower()

    @field_validator("title")
    @classmethod
    def trim_title(cls, v: Optional[str]) -> Optional[str]:
        if v and len(v) > MAX_ARTIFACT_TITLE_LENGTH:
            return v[: MAX_ARTIFACT_TITLE_LENGTH - 3] + "..."
        return v
'''

    if layer == "plugin":
        code += f'''

class PluginOutputWithArtifacts(BaseModel):
    status: int = Field(200, description="The status code of the plugin output.")
    data: Dict = Field(default_factory=dict, description="The data content of the plugin output.")
    artifacts: List[Artifact] = Field(
        default_factory=list,
        description="The list of artifacts generated by the plugin.",
    )


_MIME_TYPE_MAP = {{
{chr(10).join(type_map_lines)}
}}


def _guess_mime_type_from_url(url: str) -> str:
    lower_url = url.lower()
    for ext, mime in _MIME_TYPE_MAP.items():
        if f".{{ext}}" in lower_url:
            return mime
    return "application/octet-stream"


def _guess_mime_type_from_content(content: str) -> str:
    try:
        import json
        json.loads(content)
        return "application/json"
    except Exception:
        pass
    if content.strip().startswith("<!DOCTYPE") or content.strip().startswith("<html"):
        return "text/html"
    if content.strip().startswith("```"):
        return "text/markdown"
    return "text/plain"


def convert_legacy_data_to_artifacts(data: Dict) -> List[Artifact]:
    """
    Convert legacy plugin output data to standard artifacts.
    Supports: url, image_url, file_url, content, text, json, table fields.
    """
    artifacts: List[Artifact] = []

    if "url" in data and isinstance(data["url"], str):
        url = data["url"]
        mime_type = _guess_mime_type_from_url(url)
        artifact_type = ArtifactType.FILE
        if mime_type.startswith("image/"):
            artifact_type = ArtifactType.IMAGE
        elif mime_type.startswith("text/"):
            artifact_type = ArtifactType.TEXT

        artifacts.append(
            Artifact(
                type=artifact_type,
                mime_type=mime_type,
                title=data.get("title") or data.get("name") or "File",
                download_url=url,
                preview_url=url if artifact_type == ArtifactType.IMAGE else None,
                size=data.get("size"),
                metadata={{k: v for k, v in data.items() if k not in {{"url", "title", "name", "size"}}}},
            )
        )

    elif "image_url" in data and isinstance(data["image_url"], str):
        url = data["image_url"]
        artifacts.append(
            Artifact(
                type=ArtifactType.IMAGE,
                mime_type=_guess_mime_type_from_url(url),
                title=data.get("title") or "Image",
                download_url=url,
                preview_url=url,
                size=data.get("size"),
                metadata={{k: v for k, v in data.items() if k not in {{"image_url", "title", "size"}}}},
            )
        )

    elif "file_url" in data and isinstance(data["file_url"], str):
        url = data["file_url"]
        artifacts.append(
            Artifact(
                type=ArtifactType.FILE,
                mime_type=_guess_mime_type_from_url(url),
                title=data.get("title") or data.get("name") or "File",
                download_url=url,
                size=data.get("size"),
                metadata={{k: v for k, v in data.items() if k not in {{"file_url", "title", "name", "size"}}}},
            )
        )

    elif "json" in data and isinstance(data["json"], (dict, list)):
        import json
        json_str = json.dumps(data["json"], ensure_ascii=False)
        artifacts.append(
            Artifact(
                type=ArtifactType.JSON,
                mime_type="application/json",
                title=data.get("title") or "JSON Data",
                content=json_str,
                size=len(json_str.encode("utf-8")),
                metadata={{k: v for k, v in data.items() if k not in {{"json", "title"}}}},
            )
        )

    elif "table" in data and isinstance(data["table"], list):
        import json
        table_str = json.dumps(data["table"], ensure_ascii=False)
        artifacts.append(
            Artifact(
                type=ArtifactType.TABLE,
                mime_type="application/json",
                title=data.get("title") or "Table Data",
                content=table_str,
                size=len(table_str.encode("utf-8")),
                metadata={{k: v for k, v in data.items() if k not in {{"table", "title"}}}},
            )
        )

    elif "content" in data and isinstance(data["content"], str):
        content = data["content"]
        mime_type = _guess_mime_type_from_content(content)
        artifact_type = ArtifactType.TEXT
        if mime_type == "application/json":
            artifact_type = ArtifactType.JSON

        artifacts.append(
            Artifact(
                type=artifact_type,
                mime_type=mime_type,
                title=data.get("title") or "Content",
                content=content,
                size=len(content.encode("utf-8")),
                metadata={{k: v for k, v in data.items() if k not in {{"content", "title", "type"}}}},
            )
        )

    elif "text" in data and isinstance(data["text"], str):
        text = data["text"]
        artifacts.append(
            Artifact(
                type=ArtifactType.TEXT,
                mime_type="text/plain",
                title=data.get("title") or "Text",
                content=text,
                size=len(text.encode("utf-8")),
                metadata={{k: v for k, v in data.items() if k not in {{"text", "title"}}}},
            )
        )

    return artifacts


def summarize_artifact(artifact: Artifact, max_content_length: int = MAX_ARTIFACT_CONTENT_LENGTH) -> Artifact:
    """
    Truncate artifact content and title if they exceed maximum lengths.
    """
    if artifact.content and len(artifact.content) > max_content_length:
        truncated = artifact.content[:max_content_length]
        artifact.content = truncated + "..."
        if artifact.size is None:
            artifact.size = len(artifact.content.encode("utf-8"))

    if artifact.title and len(artifact.title) > MAX_ARTIFACT_TITLE_LENGTH:
        artifact.title = artifact.title[: MAX_ARTIFACT_TITLE_LENGTH - 3] + "..."

    return artifact


def normalize_and_summarize_artifacts(
    artifacts: Optional[List[Artifact]],
    legacy_data: Optional[Dict] = None,
) -> List[Artifact]:
    """
    Normalize and summarize artifacts.
    First tries to process new artifacts, falls back to legacy data conversion.
    Validates against shared JSON Schema at runtime if available.
    """
    result: List[Artifact] = []

    if artifacts:
        if HAS_RUNTIME_SCHEMA_VALIDATION:
            artifact_dicts = [a.model_dump() for a in artifacts]
            is_valid, errors = _contract_validate_artifact_list(artifact_dicts)
            if not is_valid:
                import logging
                logger = logging.getLogger(__name__)
                logger.warning("Artifact schema validation failed: %s", errors)

        for artifact in artifacts:
            try:
                summarize_artifact(artifact)
                result.append(artifact)
            except Exception:
                continue

    if not result and legacy_data:
        result = convert_legacy_data_to_artifacts(legacy_data)
        for artifact in result:
            summarize_artifact(artifact)

    if len(result) > MAX_ARTIFACTS_PER_TOOL:
        result = result[:MAX_ARTIFACTS_PER_TOOL]

    return result
'''

    else:  # backend
        code += f'''

def _default_mime_type_for_type(artifact_type: str) -> str:
    """
    Default MIME types for each artifact type when not explicitly provided.
    Source: contracts/artifact/v1.0.json#/properties/defaultMimeTypes
    """
    type_map = {{
{chr(10).join(default_mime_lines)}
    }}
    return type_map.get(artifact_type, "application/octet-stream")


def normalize_artifact(artifact: Dict[str, Any]) -> Artifact:
    """
    Normalize a raw artifact dict to an Artifact model instance.
    Validates against the shared schema and applies defaults.
    """
    if "type" not in artifact:
        raise ValueError("Artifact type is required")
    if "mime_type" not in artifact:
        artifact["mime_type"] = _default_mime_type_for_type(artifact["type"])
    if "metadata" not in artifact:
        artifact["metadata"] = {{}}

    return Artifact(**artifact)


def summarize_artifact(artifact: Artifact, max_content_length: int = MAX_ARTIFACT_CONTENT_LENGTH) -> Artifact:
    """
    Truncate artifact content and title if they exceed maximum lengths.
    """
    if artifact.content and len(artifact.content) > max_content_length:
        truncated = artifact.content[:max_content_length]
        artifact.content = truncated + "..."
        if artifact.size is None:
            artifact.size = len(artifact.content.encode("utf-8"))

    if artifact.title and len(artifact.title) > MAX_ARTIFACT_TITLE_LENGTH:
        artifact.title = artifact.title[: MAX_ARTIFACT_TITLE_LENGTH - 3] + "..."

    return artifact


def parse_and_normalize_artifacts(
    artifacts_data: Optional[List[Dict[str, Any]]],
) -> List[Artifact]:
    """
    Parse and normalize artifacts from raw dict data.
    Only validates and summarizes - legacy conversion is done at plugin layer.
    Validates against shared JSON Schema at runtime if available.
    """
    result: List[Artifact] = []

    if artifacts_data:
        if HAS_RUNTIME_SCHEMA_VALIDATION:
            is_valid, errors = _contract_validate_artifact_list(artifacts_data)
            if not is_valid:
                import logging
                logger = logging.getLogger(__name__)
                logger.warning("Artifact schema validation failed: %s", errors)

        for artifact_dict in artifacts_data:
            try:
                artifact = normalize_artifact(artifact_dict)
                artifact = summarize_artifact(artifact)
                result.append(artifact)
            except Exception:
                continue

    if len(result) > MAX_ARTIFACTS_PER_TOOL:
        result = result[:MAX_ARTIFACTS_PER_TOOL]

    return result
'''

    return code


def generate_typescript_types(schema: dict) -> str:
    """Generate the frontend/src/types/artifact.ts file — re-exports from npm package."""
    return f'''// AUTO-GENERATED RE-EXPORT — DO NOT EDIT MANUALLY
//
// Source package: @taskingai/contracts v{schema["version"]}
// Canonical schema: contracts/artifact/v1.0.json
//
// This file re-exports types from the shared @taskingai/contracts npm package.
// The actual definitions live in contracts/npm/src/artifact/types.ts and are
// embedded inside the published package. This keeps frontend independent —
// no Python or external contracts/ directory access is required for build.
//
// To regenerate: cd ../contracts/npm && npm run build

export {{
  isArtifactType,
  ARTIFACT_TYPES,
  ARTIFACT_CONSTANTS,
  MAX_ARTIFACT_CONTENT_LENGTH,
  MAX_ARTIFACT_TITLE_LENGTH,
  MAX_ARTIFACTS_PER_TOOL,
  DEFAULT_MIME_TYPES,
  MIME_TYPE_MAP,
  SCHEMA_VERSION,
  PACKAGE_VERSION,
  validateArtifact,
  validateArtifactList,
  loadSchema,
  getSchemaVersion,
}} from '@taskingai/contracts';

export type {{
  ArtifactType,
  Artifact,
  ArtifactList,
  MessageContent,
  Message,
  ValidationResult,
}} from '@taskingai/contracts';
'''


def generate_npm_types(schema: dict) -> str:
    """Generate the canonical TypeScript types for the @taskingai/contracts npm package."""
    constants = schema["properties"]["constants"]["properties"]
    default_mime_types = schema["properties"]["defaultMimeTypes"]["properties"]
    mime_type_map = schema["properties"]["mimeTypeMap"]["properties"]
    artifact_types = schema["definitions"]["ArtifactType"]["enum"]

    max_content = constants["MAX_ARTIFACT_CONTENT_LENGTH"]["const"]
    max_title = constants["MAX_ARTIFACT_TITLE_LENGTH"]["const"]
    max_artifacts = constants["MAX_ARTIFACTS_PER_TOOL"]["const"]

    types_str = " | ".join(f"'{t}'" for t in artifact_types)
    types_arr = ", ".join(f"'{t}'" for t in artifact_types)

    mime_map_lines = []
    for ext, mime_obj in mime_type_map.items():
        mime_value = mime_obj["const"] if isinstance(mime_obj, dict) and "const" in mime_obj else mime_obj
        mime_map_lines.append(f"  '{ext}': '{mime_value}',")

    default_mime_lines = []
    for t, mime_obj in default_mime_types.items():
        mime_value = mime_obj["const"] if isinstance(mime_obj, dict) and "const" in mime_obj else mime_obj
        default_mime_lines.append(f"  {t}: '{mime_value}',")

    return f'''// AUTO-GENERATED - DO NOT EDIT MANUALLY
// Source: contracts/artifact/v1.0.json
// Package: @taskingai/contracts v{schema["version"]}

/**
 * Artifact Protocol Constants
 * Source: contracts/artifact/v1.0.json#/properties/constants
 */
export const ARTIFACT_CONSTANTS = {{
  MAX_ARTIFACT_CONTENT_LENGTH: {max_content},
  MAX_ARTIFACT_TITLE_LENGTH: {max_title},
  MAX_ARTIFACTS_PER_TOOL: {max_artifacts},
}} as const;

export const MAX_ARTIFACT_CONTENT_LENGTH = ARTIFACT_CONSTANTS.MAX_ARTIFACT_CONTENT_LENGTH;
export const MAX_ARTIFACT_TITLE_LENGTH = ARTIFACT_CONSTANTS.MAX_ARTIFACT_TITLE_LENGTH;
export const MAX_ARTIFACTS_PER_TOOL = ARTIFACT_CONSTANTS.MAX_ARTIFACTS_PER_TOOL;

/**
 * Default MIME types for each artifact type
 * Source: contracts/artifact/v1.0.json#/properties/defaultMimeTypes
 */
export const DEFAULT_MIME_TYPES: Record<ArtifactType, string> = {{
{chr(10).join(default_mime_lines)}
}};

/**
 * File extension to MIME type mapping
 * Source: contracts/artifact/v1.0.json#/properties/mimeTypeMap
 */
export const MIME_TYPE_MAP: Record<string, string> = {{
{chr(10).join(mime_map_lines)}
}};

/**
 * The type of the artifact.
 * Only these 5 types are supported across all layers.
 * Source: contracts/artifact/v1.0.json#/definitions/ArtifactType
 */
export type ArtifactType = {types_str};

export const ARTIFACT_TYPES: readonly ArtifactType[] = [
  {types_arr},
];

/**
 * Check if a string is a valid ArtifactType.
 */
export function isArtifactType(value: unknown): value is ArtifactType {{
  return typeof value === 'string' && (ARTIFACT_TYPES as readonly string[]).includes(value);
}}

/**
 * Standard artifact data transfer object (DTO).
 * All layers must use this exact schema.
 * Source: contracts/artifact/v1.0.json#/definitions/Artifact
 */
export interface Artifact {{
  /** The type of the artifact. */
  type: ArtifactType;

  /** The MIME type of the artifact. Must be in 'type/subtype' format, lowercase. */
  mime_type: string;

  /** The display title of the artifact. Will be truncated if exceeds max length. */
  title?: string;

  /** The text content of the artifact (for text, json, table, etc.). Will be truncated if exceeds max content length. */
  content?: string;

  /** The preview image URL of the artifact. */
  preview_url?: string;

  /** The download URL of the artifact. */
  download_url?: string;

  /** The size of the artifact in bytes. */
  size?: number;

  /** Additional metadata for the artifact. */
  metadata?: Record<string, any>;
}}

/**
 * A list of artifacts with max items constraint.
 */
export type ArtifactList = Artifact[];

export interface MessageContent {{
  text: string;
  artifacts?: Artifact[];
}}

export interface Message {{
  object: string;
  assistant_id: string;
  chat_id: string;
  message_id: string;
  role: 'user' | 'assistant';
  content: MessageContent;
  num_tokens: number;
  metadata: Record<string, any>;
  created_timestamp: number;
  updated_timestamp: number;
}}

/** Schema version */
export const SCHEMA_VERSION = '{schema["version"]}';
export const PACKAGE_VERSION = '{schema["version"]}';
'''


def main():
    import sys
    import shutil
    args = sys.argv[1:]

    if "--check" in args or "--verify" in args:
        success = check_consistency()
        sys.exit(0 if success else 1)

    print(f"Loading schema from: {SCHEMA_PATH}")
    schema = load_schema()
    print(f"Schema version: {schema['version']}")

    # Generate backend code
    backend_code = generate_python_models(schema, "backend")
    BACKEND_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(BACKEND_OUTPUT, "w") as f:
        f.write(backend_code)
    print(f"✓ Generated backend: {BACKEND_OUTPUT}")

    # Generate plugin code
    plugin_code = generate_python_models(schema, "plugin")
    PLUGIN_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(PLUGIN_OUTPUT, "w") as f:
        f.write(plugin_code)
    print(f"✓ Generated plugin: {PLUGIN_OUTPUT}")

    # Generate frontend re-export wrapper
    frontend_code = generate_typescript_types(schema)
    FRONTEND_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(FRONTEND_OUTPUT, "w") as f:
        f.write(frontend_code)
    print(f"✓ Generated frontend re-export: {FRONTEND_OUTPUT}")

    # ── npm package: canonical types ─────────────────────────────────
    npm_types_code = generate_npm_types(schema)
    NPM_TYPES_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(NPM_TYPES_OUTPUT, "w") as f:
        f.write(npm_types_code)
    print(f"✓ Generated npm package types: {NPM_TYPES_OUTPUT}")

    # ── npm package: copy schema to embedded schemas dir ─────────────
    NPM_SCHEMA_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(SCHEMA_PATH, NPM_SCHEMA_OUTPUT)
    print(f"✓ Updated embedded schema in npm package: {NPM_SCHEMA_OUTPUT}")

    # ── python package: copy schema to embedded schemas dir ──────────
    PY_PKG_SCHEMA.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(SCHEMA_PATH, PY_PKG_SCHEMA)
    print(f"✓ Updated embedded schema in python package: {PY_PKG_SCHEMA}")

    print("\nAll files generated successfully!")
    print("\nNote: These files are auto-generated. To make changes:")
    print("  1. Edit contracts/artifact/v1.0.json")
    print("  2. Run: python contracts/artifact/generate_artifact_types.py")
    print("\nTo verify consistency at any time:")
    print("  python contracts/artifact/generate_artifact_types.py --check")
    print("\nTo build the npm package after regeneration:")
    print("  cd contracts/npm && npm run build")


def check_consistency() -> bool:
    """
    Check that all generated files match the current schema.
    Returns True if everything is consistent, False otherwise.
    Used in CI and startup checks.
    """
    import hashlib

    print("=== Artifact Contract Consistency Check ===")
    print()
    all_ok = True

    schema = load_schema()
    schema_version = schema["version"]

    # 1. Check constants consistency
    constants = schema["properties"]["constants"]["properties"]
    expected = {
        "MAX_ARTIFACT_CONTENT_LENGTH": constants["MAX_ARTIFACT_CONTENT_LENGTH"]["const"],
        "MAX_ARTIFACT_TITLE_LENGTH": constants["MAX_ARTIFACT_TITLE_LENGTH"]["const"],
        "MAX_ARTIFACTS_PER_TOOL": constants["MAX_ARTIFACTS_PER_TOOL"]["const"],
    }

    layers = [
        ("backend", BACKEND_OUTPUT, "python"),
        ("plugin", PLUGIN_OUTPUT, "python"),
        ("frontend", FRONTEND_OUTPUT, "typescript"),
    ]

    for layer_name, output_path, file_type in layers:
        print(f"--- Checking {layer_name} ({output_path.relative_to(Path(__file__).parent.parent.parent)}) ---")

        if not output_path.exists():
            print(f"  ✗ FILE MISSING")
            all_ok = False
            continue

        content = output_path.read_text()

        # Check auto-generated header
        if "AUTO-GENERATED" not in content:
            print(f"  ✗ Missing AUTO-GENERATED header (file may have been manually edited)")
            all_ok = False
        else:
            print(f"  ✓ Auto-generated header present")

        # Check schema version
        if f"v{schema_version}" in content:
            print(f"  ✓ Schema version v{schema_version} matches")
        else:
            print(f"  ✗ Schema version mismatch (expected v{schema_version})")
            all_ok = False

        # frontend is now a re-export wrapper from @taskingai/contracts
        if layer_name == "frontend":
            if "from '@taskingai/contracts'" in content:
                print(f"  ✓ Imports from @taskingai/contracts package")
            else:
                print(f"  ✗ Missing @taskingai/contracts import (frontend should re-export from npm package)")
                all_ok = False
            if "export type {" in content and "export {" in content:
                print(f"  ✓ Re-exports both values and types")
            else:
                print(f"  ✗ Missing re-export statements")
                all_ok = False
            print()
            continue

        # Check constants
        for key, value in expected.items():
            if file_type == "python":
                pattern = f"{key} = {value}"
            else:
                pattern = f"{key}: {value}"
            if pattern in content:
                print(f"  ✓ {key} = {value}")
            else:
                print(f"  ✗ {key} mismatch (expected = {value})")
                all_ok = False

        # Check ArtifactType enum values
        expected_types = schema["definitions"]["ArtifactType"]["enum"]
        if file_type == "python":
            for t in expected_types:
                if f'= "{t}"' in content:
                    print(f"  ✓ ArtifactType.{t.upper()} present")
                else:
                    print(f"  ✗ ArtifactType.{t.upper()} missing")
                    all_ok = False
        else:
            for t in expected_types:
                if f"'{t}'" in content:
                    print(f"  ✓ ArtifactType '{t}' present")
                else:
                    print(f"  ✗ ArtifactType '{t}' missing")
                    all_ok = False

        print()

    # 2. Check python package embedded schema
    print("--- Checking python package embedded schema ---")
    if PY_PKG_SCHEMA.exists():
        embedded = PY_PKG_SCHEMA.read_text()
        source = SCHEMA_PATH.read_text()
        if hashlib.sha256(embedded.encode()).hexdigest() == hashlib.sha256(source.encode()).hexdigest():
            print("  ✓ Embedded schema matches source")
        else:
            print("  ✗ Embedded schema does NOT match source (re-run generator)")
            all_ok = False
    else:
        print("  ⚠ Embedded schema path missing (not critical for dev)")
    print()

    # 2b. Check npm package embedded schema
    print("--- Checking npm package embedded schema ---")
    if NPM_SCHEMA_OUTPUT.exists():
        embedded = NPM_SCHEMA_OUTPUT.read_text()
        source = SCHEMA_PATH.read_text()
        if hashlib.sha256(embedded.encode()).hexdigest() == hashlib.sha256(source.encode()).hexdigest():
            print("  ✓ Embedded schema matches source")
        else:
            print("  ✗ Embedded schema does NOT match source (re-run generator)")
            all_ok = False
    else:
        print("  ⚠ Embedded schema path missing (not critical for dev)")
    print()

    # 2c. Check npm package types.ts
    print("--- Checking npm package types.ts ---")
    if NPM_TYPES_OUTPUT.exists():
        npm_content = NPM_TYPES_OUTPUT.read_text()
        if "AUTO-GENERATED" in npm_content:
            print("  ✓ Auto-generated header present")
        else:
            print("  ✗ Missing AUTO-GENERATED header")
            all_ok = False

        for key, value in expected.items():
            if f"{key}: {value}" in npm_content:
                print(f"  ✓ {key} = {value}")
            else:
                print(f"  ✗ {key} mismatch (expected = {value})")
                all_ok = False

        expected_types = schema["definitions"]["ArtifactType"]["enum"]
        for t in expected_types:
            if f"'{t}'" in npm_content:
                print(f"  ✓ ArtifactType '{t}' present")
            else:
                print(f"  ✗ ArtifactType '{t}' missing")
                all_ok = False
    else:
        print("  ⚠ npm types.ts missing (not critical for dev)")
    print()

    # 3. Verify we can import taskingai_contracts (python)
    print("--- Checking taskingai_contracts python package import ---")
    try:
        from taskingai_contracts import (
            __schema_version__,
            ArtifactType,
            MAX_ARTIFACT_CONTENT_LENGTH,
            validate_artifact,
        )
        print(f"  ✓ Package importable (schema v{__schema_version__})")

        # Quick validation test
        test_art = {"type": "text", "mime_type": "text/plain", "title": "Test"}
        is_valid, _ = validate_artifact(test_art)
        if is_valid:
            print(f"  ✓ Runtime validation works")
        else:
            print(f"  ✗ Runtime validation failed unexpectedly")
            all_ok = False
    except ImportError as e:
        print(f"  ⚠ Package not importable: {e} (install with: pip install -e contracts/python)")
    print()

    # 3b. Check npm package can be imported/validated (via node check-contracts script if built)
    print("--- Checking @taskingai/contracts npm package ---")
    npm_check_script = NPM_PKG / "dist" / "check-contracts.js"
    if npm_check_script.exists():
        import subprocess
        result = subprocess.run(
            ["node", str(npm_check_script)],
            capture_output=True, text=True, cwd=str(NPM_PKG)
        )
        if result.returncode == 0:
            print("  ✓ npm check-contracts passes")
        else:
            print(f"  ✗ npm check-contracts failed (rc={result.returncode})")
            print(f"    stderr: {result.stderr[-200:]}")
            all_ok = False
    else:
        print("  ⚠ npm package not built yet (run: cd contracts/npm && npm install && npm run build)")
    print()

    if all_ok:
        print("✅ ALL CHECKS PASSED — artifact contract is consistent across all layers")
    else:
        print("❌ CHECKS FAILED — run `python contracts/artifact/generate_artifact_types.py` to regenerate")

    return all_ok


if __name__ == "__main__":
    main()
